
require "user.options"
require "user.keymappings"
require "user.plugins"
require "user.colorscheme"
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.trouble"
require "user.treesitter"
require "user.autopairs"
require "user.surround"
require "user.comment"
require "user.gitsigns"
require "user.tree"
require "user.bufferline"
require "user.lualine"
require "user.project"
